apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: node-operator.v0.0.1
  namespace: placeholder
  annotations:
    alm-examples: >-
      [{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"","metadata":{"name":"nodejs.demo.example.com"},"spec":{"group":"demo.example.com","names":{"kind":"Nodejs","listKind":"NodejsList","plural":"nodejs","singular":"nodejs"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true}]}},{"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"","metadata":{"name":"nodejs.demo.example.com"},"spec":{"group":"demo.example.com","names":{"kind":"Nodejs","listKind":"NodejsList","plural":"nodejs","singular":"nodejs"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true}]}},{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"","kind":"","metadata":{"name":""},"spec":{}},{"apiVersion":"","kind":"Nodejs","metadata":{"name":""},"spec":{}}]
    categories: ''
    certified: 'false'
    description: >-
      build and develop nodejs application and using operators for managing the
      application
    containerImage: ''
    support: ''
    capabilities: Seamless Upgrades
    repository: ''
spec:
  displayName: NodejsOperator
  description: |
    ## About the managed application
    ## About this Operator
    ## Prerequisites for enabling this Operator
  maturity: planning
  version: 0.0.1
  replaces: ''
  minKubeVersion: 1.11.0
  keywords: []
  maintainers:
    - name: ''
      email: ''
  provider:
    name: 'ACME,inc'
  labels: {}
  selector:
    matchLabels: {}
  links:
    - name: Blog
      url: >-
        https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md
  icon:
    base64data: ''
    mediatype: ''
  customresourcedefinitions:
    owned:
      - name: nodejs.demo.example.com
        displayName: Nodejs
        kind: Nodejs
        version: v1alpha1
        description: Nodejs
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
    required: []
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: nodejs-operator
          rules:
            - apiGroups: '""'
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
      clusterPermissions:
        - serviceAccountName: nodejs-operator
          rules:
            - apiGroups: '""'
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
      deployments:
        - name: nodejs-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                k8s-app: nodejs-operator
            template:
              metadata:
                labels:
                  k8s-app: nodejs-operator
              spec:
                containers:
                  image: 'quay.io/deekshith_vemula/example:v1'
                  imagePullPolicy: Always
                  name: nodejs-operator
                  resources:
                    limits:
                      cpu: 200m
                      memory: 100Mi
                    requests:
                      cpu: 100m
                      memory: 50Mi
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: OPERATOR_NAME
                      value: nodejs-operator
                imagePullSecrets:
                  - name: ''
                nodeSelector:
                  beta.kubernetes.io/os: linux
                serviceAccountName: nodejs-operator
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
